### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'empty.idx'

### ISSUE THREAD

**Issue by niconavarrete** [pettarin/penelope#1] opened 2014-09-14 12:58 UTC
Hi, 

I'm trying to convert minirae to odyssy format and getting this error:
$ python src/penelope.py -p "miniRAE-2246_r2_eSDICT" -f es -t es --output-odyssey  -d
[INFO] Input dictionary has sequence type 'x'.
[INFO] Debug mode is on.
[INFO] Starting conversion with the following parameters:

[INFO] Dictionary file: es.miniRAE-2246_r2_eSDICT.dict
[INFO] Index file:      es.miniRAE-2246_r2_eSDICT.dict.idx
[INFO] Language from:   es
[INFO] Language to:     es
[INFO] License:         GNU GPL 3
[INFO] Copyright:       GNU GPL 3
[INFO] Title:           Dictionary es -> es
[INFO] Description:     Dictionary es -> es
[INFO] Year:            2012

[INFO] Reading input dictionaries...
[INFO] Parsing the input data...
[INFO] Using the built-in parser...
[INFO] Outputting in Odyssey format to file...
Traceback (most recent call last):
  File "src/penelope.py", line 2096, in <module>
    main()
  File "src/penelope.py", line 2041, in main
    write_to_odyssey_format(config, parsed_data, collation, debug)
  File "src/penelope.py", line 376, in write_to_odyssey_format
    input_file = open('empty.idx', "rb")
IOError: [Errno 2] No such file or directory: 'empty.idx'

**Comment by pettarin** [comment] 2014-09-14 13:55
Change the working directory to `src/` (`$ cd src/`) and try again. You might want to copy your input files into `src/` so that you can invoke:

`$ cd src/`
`$ python penelope.py -p "miniRAE-2246_r2_eSDICT" -f es -t es --output-odyssey -d`

**Comment by pettarin** [comment] 2014-09-14 13:56
Reopening, in case some future maintainer would like to address this issue. The problem is that the current script tries to load `empty.idx` from the `$CWD`, but it should actually look inside the `arg[0]` directory.

**Comment by niconavarrete** [comment] 2014-09-14 19:10
Thanks a lot, with that $CWD  change to $_  is working and i managed to install the 'minirae' dic, just to note, cpying the files in the dictionaries folder of the cybook, and changing the language to the dictiony's language, 'es' in my case.

Easier to change dir than changing script ..

def getScriptPath():
    return os.path.dirname(os.path.realpath(sys.argv[0]))
http://stackoverflow.com/questions/4934806/python-how-to-find-scripts-directory

Thank again, let it open for google searches.

**Comment by pettarin** [comment] 2015-01-25 20:06
Closing, as I fixed this issue myself in v2.0.1 . Thank you for contributing this issue report and the above link.

**Closed as completed by pettarin** 2015-01-25 20:06 UTC
